name: CI/CD to EC2 via CodeDeploy (FastAPI)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: ap-northeast-2
  S3_BUCKET: bssm-fastapi-artifacts-19
  APP_NAME: fastapi-cicd-test
  DEPLOY_GROUP: fastapiapp-prod
  PACKAGE: fastapiapp-${{ github.sha }}.zip

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: (optional) Quick check
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # pytest, ruff 등을 원하면 여기에 추가

      - name: Make artifact for deployment
        run: |
          mkdir -p artifact/scripts
          cp main.py requirements.txt appspec.yml artifact/
          cp -a scripts/. artifact/scripts/
          cd artifact && zip -r ../${{ env.PACKAGE }} . && cd ..

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_PRIVATE_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
          # role-to-assume: arn:aws:iam::<account-id>:role/CodeDeployRole

      - name: Upload artifact to S3
        run: aws s3 cp ${{ env.PACKAGE }} s3://${{ env.S3_BUCKET }}/${{ env.PACKAGE }}

      - name: Trigger AWS CodeDeploy
        run: |
          aws deploy create-deployment \
            --application-name ${{ env.APP_NAME }} \
            --deployment-group-name ${{ env.DEPLOY_GROUP }} \
            --s3-location bucket=${{ env.S3_BUCKET }},key=${{ env.PACKAGE }},bundleType=zip
